export const API_URL = 'https://status.geonorge.no/statistikk/_api'
export const DATE_DEFAULT = 'YYYY-MM-DD'
export const DATE_INPUT = 'YYYY-MM-DD[T]HH:mm:ss.SSS'
export const DATE_OUTPUT = 'DD.MM.YY'
export const DEFAULT_DURATION = 'PT24H'
