export const API_URL = 'https://status.geonorge.no/statistikkApi'
export const API_URL_ALT = 'https://status.geonorge.no/api'
export const DATE_DEFAULT = 'YYYY-MM-DD'
export const DATE_INPUT = 'YYYY-MM-DD[T]HH:mm:ss'
export const DATE_OUTPUT = 'DD.MM.YY'
export const DEFAULT_DURATION = '24H'
